### ISSUE TITLE
AutoFocusStateMachine implementation

### ISSUE THREAD

**Issue by gilles-yvetot** [halide/CVPR2015#1]
Hello there,

I am trying to customize the way the auto focus work on my camera app and I found your auto focus manager (AutoFocusStateMachine). I have read everything and understand what every function does but I dont see how can I implement that with the Camera2BasicFragment ... 

What I meant is the functions describe behaviors like "Once active AF scanning starts AutoFocusStateListener#onAutoFocusScan will be invoked." but I dont know how the CameraDevice is binded to all these functions. I am looking for the bridge between Camera2BasicFragment and AutoFocusStateMachine

Thanks again!

**Comment by jiawen** [comment]
Hello,

My apologies for the delay but I was traveling without email access.

AutoFocusStateMachine is part of the Android platform and we haven't used it ourselves. But looking at the code, I think the intended use is:
- Declare your own class that implements AutoFocusStateMachine.AutoFocusStateListener. This will let you receive higher level useful notifications on AF events.
- Instantiate your subclass and pass it to the AutoFocusStateMachine constructor.
- In Camera2BasicFragment (https://github.com/halide/Halide/blob/master/apps/HelloAndroidCamera2/src/com/example/helloandroidcamera2/Camera2BasicFragment.java#L214), call mAFStateMachine.onCaptureCompleted(), passing it the CaptureResult. This updates the state machine.
- Typically when you want to capture a shot, you'll want to lock the autofocus. In which case, call mAFStateMachine.lockAutoFocus().
  - repeatingBuilder is your usual viewfinder repeating request builder. It is modified in place.
  - I'm not 100% sure but I believe requestBuilder is the new builder that you should submit exactly once.
- Wait until your listener subclass's onAutoFocusSuccess() is called. Once that's done (or times out), take your shot (by submitting another capture request).
- Unlock the lens.

When the user does a tap to focus:
- Call mAFStateMachine.setActiveAutoFocus(). This triggers an ACTIVE SCAN where the AF system will attempt to focus on the spot that was touched. There is a key in CaptureRequest.Builder where you set the coordinates (this API seems to be poorly designed).
- After a timeout, you'll probably want to call setPassiveAutoFocus() to go back to the "normal" passive autofocus mode, where the camera periodically scans for objects to focus on (and likely also refocuses based on changes to image content or gyro).

I hope that answers your questions.

**Comment by gilles-yvetot** [comment]
That answers perfectly my question! I need to first find out why the Camera2Basic is not working on one of the testing phones I have (Samsung S5) and I'll get back to you as soon as I can. Thanksss

**Comment by jiawen** [comment]
Ah, I think the issue is that the Samsung Galaxy S5 does not yet support the camera2 API (despite running Android 5.0 Lollipop). I think at the moment, it's limited to the Nexus 5, Nexus 6, Nexus 5X, Nexus 6P, the LG G4, and the Samsung Galaxy S6 Edge. I'm not sure if the non-edge S6 supports it. You may able to query for capabilities (FULL, LIMITED, LEGACY) via the API.

**Comment by gilles-yvetot** [comment]
That's what I thought too at the beginning, but I have exactly the same listed capabilities on a working device and on a non-working device...
