### ISSUE TITLE
blur.cpp no performance increase

### ISSUE THREAD

**Issue by Computational-Camera** [halide/CVPR2015#4]
if line 76 change from
cv::Mat input_image = cv::Mat::zeros(in.width(), in.height(), CV_32FC3);
to 
cv::Mat input_image = cv::Mat::zeros(in.width(), in.height(), CV_8UC3);

the actual performance comparison result is Opencv's implementation is 2 times faster than Halide, even only one thread is used in the Opencv while Halide use all the threads to compute the blur.

**Comment by abadams** [comment]
Well yeah, that's a different algorithm. The benchmark is a floating point blur.

**Comment by Computational-Camera** [comment]
> Well yeah, that's a different algorithm. The benchmark is a floating point blur.

thanks Adam, just wonder if there is integer version (unsigned char) ? It would be really interesting to see the performance comparison.

**Comment by jrk** [comment]
It should be relatively easy to at least take a first crack at it by changing the Halide algorithm to similarly use `uint8_t` input and output data:

```
Image<uint8_t> in = ...
...
Image<uint8_t> output(...)
```

and then changing the two `vectorize` directives to 32 or 64.

No guarantees that's the most efficient solution, but it is a trivial first rewrite which should perform significantly faster.
