### ISSUE TITLE
No improvement in computation time

### ISSUE THREAD

**Issue by AndreiBaraian** [halide/CVPR2015#5]
Hello,

I was trying to play with the brighten function and test to see how it performs on my machine. I followed the instructions (downloaded the binary release, untar it and compiled with the provided instruction. I have tested it on a 1920x1080 image by commenting and uncommenting the line `brighter.vectorize(x, 8).parallel(y);`. The results were similar, sometimes the version with no vectorization and parallelization was actually faster. Also, the first iteration took 550ms, while all the other ones took 0-1ms. 

The idea was also to compare it with the PIL Image Enhancement Brightness function to see if I can get better time. So far, the PIL function is by one order of magnitude faster, which is quite surprising to me. 

I guess there must be something that I do wrong. I am quite new to this, but eager to learn. I was wondering, would I get better results if I would build Halide from source with LLVM instead of using the binary release? Then again, I suppose the computation is anyway just a simple addition and probably LLVM already does the vectorization quite well, hence that would explain the no difference between the vectorization version and the one without it. 

One more thing: By compiling the .cpp file like in the instruction, does it mean that it is actually JIT compiled? Should it be wrapped inside a Generator, so that it would be only AOT compiled?

Thanks!

**Update 1** After compiling the brighten function as in Lesson 10, there was a significant speed-up, by a factor of 2. Also, if I now comment the vectorization and parallelization, it is slower. I have also increased the image size (5160x2880). 

However, the loading and saving of the image is slower in Halide then in PIL. I'll try to look into that as well.

**Comment by zvookin** [comment]
Image loading will not be optimized in Halide. It is provided solely for getting inputs for testing and benchmarking. Thus measuring the time for that is not productive.

I wouldn't expect Halide to win over an already optimized brightness transform on a platform where it is already optimized and in native code. (There isn't much work there and it's not hard to optimize.) Halide should match the best performance and allows specializing to uncommon datatypes, etc. The real win is having a pipeline of many operations or a more complex operation written in Halide and well scheduled.

It would help to get specifics on the hardware and links to the code you are using. ("lesson 10" is specific enough, but I'm not sure the code for the first part. It seems very likely it was using JIT, not AOT.)

**Comment by AndreiBaraian** [comment]
Thanks a lot for the info, it helps me understanding what Halide was designed for. Indeed, I was using JIT  and not AOT, hence the decrease in performance.
